#ifndef MACRO_UNROLLING
#define MACRO_UNROLLING

/**
 * This file is intentionally ugly so that other files dont have to be!
 * Used for preprocessor macro unrolling & repeated-injection
 * Source: https://stackoverflow.com/questions/28231743/self-unrolling-macro-loop-in-c-c
 * 
 * Calls the supplied predicate macro (X) N Number of times with the argument N-1 for
 * each iteration... 
 * 
 * Example: 
 *      M_REPEAT_CALL(3, ECHO) -> expands to -> printf("0"); printf("1"); printf("2");
 *      where ECHO is defined as: #define ECHO(N) printf("N");
 * 
 * Code generated by the following Javascript snippet:
 * 
 *  let code = ``;
 *  for (let i=1; i<256; i++) {
 *    code+=`#define M_REPEAT_CALL_${i+1}(X) M_REPEAT_CALL_${i}(X) X(${i})\n`;
 *  }
 *  console.log(code);
 */

#define M_REPEAT_CALL_1(X) X(0)
#define M_REPEAT_CALL_2(X) \
    M_REPEAT_CALL_1(X)     \
    X(1)
#define M_REPEAT_CALL_3(X) \
    M_REPEAT_CALL_2(X)     \
    X(2)
#define M_REPEAT_CALL_4(X) \
    M_REPEAT_CALL_3(X)     \
    X(3)
#define M_REPEAT_CALL_5(X) \
    M_REPEAT_CALL_4(X)     \
    X(4)
#define M_REPEAT_CALL_6(X) \
    M_REPEAT_CALL_5(X)     \
    X(5)
#define M_REPEAT_CALL_7(X) \
    M_REPEAT_CALL_6(X)     \
    X(6)
#define M_REPEAT_CALL_8(X) \
    M_REPEAT_CALL_7(X)     \
    X(7)
#define M_REPEAT_CALL_9(X) \
    M_REPEAT_CALL_8(X)     \
    X(8)
#define M_REPEAT_CALL_10(X) \
    M_REPEAT_CALL_9(X)      \
    X(9)
#define M_REPEAT_CALL_11(X) \
    M_REPEAT_CALL_10(X)     \
    X(10)
#define M_REPEAT_CALL_12(X) \
    M_REPEAT_CALL_11(X)     \
    X(11)
#define M_REPEAT_CALL_13(X) \
    M_REPEAT_CALL_12(X)     \
    X(12)
#define M_REPEAT_CALL_14(X) \
    M_REPEAT_CALL_13(X)     \
    X(13)
#define M_REPEAT_CALL_15(X) \
    M_REPEAT_CALL_14(X)     \
    X(14)
#define M_REPEAT_CALL_16(X) \
    M_REPEAT_CALL_15(X)     \
    X(15)
#define M_REPEAT_CALL_17(X) \
    M_REPEAT_CALL_16(X)     \
    X(16)
#define M_REPEAT_CALL_18(X) \
    M_REPEAT_CALL_17(X)     \
    X(17)
#define M_REPEAT_CALL_19(X) \
    M_REPEAT_CALL_18(X)     \
    X(18)
#define M_REPEAT_CALL_20(X) \
    M_REPEAT_CALL_19(X)     \
    X(19)
#define M_REPEAT_CALL_21(X) \
    M_REPEAT_CALL_20(X)     \
    X(20)
#define M_REPEAT_CALL_22(X) \
    M_REPEAT_CALL_21(X)     \
    X(21)
#define M_REPEAT_CALL_23(X) \
    M_REPEAT_CALL_22(X)     \
    X(22)
#define M_REPEAT_CALL_24(X) \
    M_REPEAT_CALL_23(X)     \
    X(23)
#define M_REPEAT_CALL_25(X) \
    M_REPEAT_CALL_24(X)     \
    X(24)
#define M_REPEAT_CALL_26(X) \
    M_REPEAT_CALL_25(X)     \
    X(25)
#define M_REPEAT_CALL_27(X) \
    M_REPEAT_CALL_26(X)     \
    X(26)
#define M_REPEAT_CALL_28(X) \
    M_REPEAT_CALL_27(X)     \
    X(27)
#define M_REPEAT_CALL_29(X) \
    M_REPEAT_CALL_28(X)     \
    X(28)
#define M_REPEAT_CALL_30(X) \
    M_REPEAT_CALL_29(X)     \
    X(29)
#define M_REPEAT_CALL_31(X) \
    M_REPEAT_CALL_30(X)     \
    X(30)
#define M_REPEAT_CALL_32(X) \
    M_REPEAT_CALL_31(X)     \
    X(31)
#define M_REPEAT_CALL_33(X) \
    M_REPEAT_CALL_32(X)     \
    X(32)
#define M_REPEAT_CALL_34(X) \
    M_REPEAT_CALL_33(X)     \
    X(33)
#define M_REPEAT_CALL_35(X) \
    M_REPEAT_CALL_34(X)     \
    X(34)
#define M_REPEAT_CALL_36(X) \
    M_REPEAT_CALL_35(X)     \
    X(35)
#define M_REPEAT_CALL_37(X) \
    M_REPEAT_CALL_36(X)     \
    X(36)
#define M_REPEAT_CALL_38(X) \
    M_REPEAT_CALL_37(X)     \
    X(37)
#define M_REPEAT_CALL_39(X) \
    M_REPEAT_CALL_38(X)     \
    X(38)
#define M_REPEAT_CALL_40(X) \
    M_REPEAT_CALL_39(X)     \
    X(39)
#define M_REPEAT_CALL_41(X) \
    M_REPEAT_CALL_40(X)     \
    X(40)
#define M_REPEAT_CALL_42(X) \
    M_REPEAT_CALL_41(X)     \
    X(41)
#define M_REPEAT_CALL_43(X) \
    M_REPEAT_CALL_42(X)     \
    X(42)
#define M_REPEAT_CALL_44(X) \
    M_REPEAT_CALL_43(X)     \
    X(43)
#define M_REPEAT_CALL_45(X) \
    M_REPEAT_CALL_44(X)     \
    X(44)
#define M_REPEAT_CALL_46(X) \
    M_REPEAT_CALL_45(X)     \
    X(45)
#define M_REPEAT_CALL_47(X) \
    M_REPEAT_CALL_46(X)     \
    X(46)
#define M_REPEAT_CALL_48(X) \
    M_REPEAT_CALL_47(X)     \
    X(47)
#define M_REPEAT_CALL_49(X) \
    M_REPEAT_CALL_48(X)     \
    X(48)
#define M_REPEAT_CALL_50(X) \
    M_REPEAT_CALL_49(X)     \
    X(49)
#define M_REPEAT_CALL_51(X) \
    M_REPEAT_CALL_50(X)     \
    X(50)
#define M_REPEAT_CALL_52(X) \
    M_REPEAT_CALL_51(X)     \
    X(51)
#define M_REPEAT_CALL_53(X) \
    M_REPEAT_CALL_52(X)     \
    X(52)
#define M_REPEAT_CALL_54(X) \
    M_REPEAT_CALL_53(X)     \
    X(53)
#define M_REPEAT_CALL_55(X) \
    M_REPEAT_CALL_54(X)     \
    X(54)
#define M_REPEAT_CALL_56(X) \
    M_REPEAT_CALL_55(X)     \
    X(55)
#define M_REPEAT_CALL_57(X) \
    M_REPEAT_CALL_56(X)     \
    X(56)
#define M_REPEAT_CALL_58(X) \
    M_REPEAT_CALL_57(X)     \
    X(57)
#define M_REPEAT_CALL_59(X) \
    M_REPEAT_CALL_58(X)     \
    X(58)
#define M_REPEAT_CALL_60(X) \
    M_REPEAT_CALL_59(X)     \
    X(59)
#define M_REPEAT_CALL_61(X) \
    M_REPEAT_CALL_60(X)     \
    X(60)
#define M_REPEAT_CALL_62(X) \
    M_REPEAT_CALL_61(X)     \
    X(61)
#define M_REPEAT_CALL_63(X) \
    M_REPEAT_CALL_62(X)     \
    X(62)
#define M_REPEAT_CALL_64(X) \
    M_REPEAT_CALL_63(X)     \
    X(63)
#define M_REPEAT_CALL_65(X) \
    M_REPEAT_CALL_64(X)     \
    X(64)
#define M_REPEAT_CALL_66(X) \
    M_REPEAT_CALL_65(X)     \
    X(65)
#define M_REPEAT_CALL_67(X) \
    M_REPEAT_CALL_66(X)     \
    X(66)
#define M_REPEAT_CALL_68(X) \
    M_REPEAT_CALL_67(X)     \
    X(67)
#define M_REPEAT_CALL_69(X) \
    M_REPEAT_CALL_68(X)     \
    X(68)
#define M_REPEAT_CALL_70(X) \
    M_REPEAT_CALL_69(X)     \
    X(69)
#define M_REPEAT_CALL_71(X) \
    M_REPEAT_CALL_70(X)     \
    X(70)
#define M_REPEAT_CALL_72(X) \
    M_REPEAT_CALL_71(X)     \
    X(71)
#define M_REPEAT_CALL_73(X) \
    M_REPEAT_CALL_72(X)     \
    X(72)
#define M_REPEAT_CALL_74(X) \
    M_REPEAT_CALL_73(X)     \
    X(73)
#define M_REPEAT_CALL_75(X) \
    M_REPEAT_CALL_74(X)     \
    X(74)
#define M_REPEAT_CALL_76(X) \
    M_REPEAT_CALL_75(X)     \
    X(75)
#define M_REPEAT_CALL_77(X) \
    M_REPEAT_CALL_76(X)     \
    X(76)
#define M_REPEAT_CALL_78(X) \
    M_REPEAT_CALL_77(X)     \
    X(77)
#define M_REPEAT_CALL_79(X) \
    M_REPEAT_CALL_78(X)     \
    X(78)
#define M_REPEAT_CALL_80(X) \
    M_REPEAT_CALL_79(X)     \
    X(79)
#define M_REPEAT_CALL_81(X) \
    M_REPEAT_CALL_80(X)     \
    X(80)
#define M_REPEAT_CALL_82(X) \
    M_REPEAT_CALL_81(X)     \
    X(81)
#define M_REPEAT_CALL_83(X) \
    M_REPEAT_CALL_82(X)     \
    X(82)
#define M_REPEAT_CALL_84(X) \
    M_REPEAT_CALL_83(X)     \
    X(83)
#define M_REPEAT_CALL_85(X) \
    M_REPEAT_CALL_84(X)     \
    X(84)
#define M_REPEAT_CALL_86(X) \
    M_REPEAT_CALL_85(X)     \
    X(85)
#define M_REPEAT_CALL_87(X) \
    M_REPEAT_CALL_86(X)     \
    X(86)
#define M_REPEAT_CALL_88(X) \
    M_REPEAT_CALL_87(X)     \
    X(87)
#define M_REPEAT_CALL_89(X) \
    M_REPEAT_CALL_88(X)     \
    X(88)
#define M_REPEAT_CALL_90(X) \
    M_REPEAT_CALL_89(X)     \
    X(89)
#define M_REPEAT_CALL_91(X) \
    M_REPEAT_CALL_90(X)     \
    X(90)
#define M_REPEAT_CALL_92(X) \
    M_REPEAT_CALL_91(X)     \
    X(91)
#define M_REPEAT_CALL_93(X) \
    M_REPEAT_CALL_92(X)     \
    X(92)
#define M_REPEAT_CALL_94(X) \
    M_REPEAT_CALL_93(X)     \
    X(93)
#define M_REPEAT_CALL_95(X) \
    M_REPEAT_CALL_94(X)     \
    X(94)
#define M_REPEAT_CALL_96(X) \
    M_REPEAT_CALL_95(X)     \
    X(95)
#define M_REPEAT_CALL_97(X) \
    M_REPEAT_CALL_96(X)     \
    X(96)
#define M_REPEAT_CALL_98(X) \
    M_REPEAT_CALL_97(X)     \
    X(97)
#define M_REPEAT_CALL_99(X) \
    M_REPEAT_CALL_98(X)     \
    X(98)
#define M_REPEAT_CALL_100(X) \
    M_REPEAT_CALL_99(X)      \
    X(99)
#define M_REPEAT_CALL_101(X) \
    M_REPEAT_CALL_100(X)     \
    X(100)
#define M_REPEAT_CALL_102(X) \
    M_REPEAT_CALL_101(X)     \
    X(101)
#define M_REPEAT_CALL_103(X) \
    M_REPEAT_CALL_102(X)     \
    X(102)
#define M_REPEAT_CALL_104(X) \
    M_REPEAT_CALL_103(X)     \
    X(103)
#define M_REPEAT_CALL_105(X) \
    M_REPEAT_CALL_104(X)     \
    X(104)
#define M_REPEAT_CALL_106(X) \
    M_REPEAT_CALL_105(X)     \
    X(105)
#define M_REPEAT_CALL_107(X) \
    M_REPEAT_CALL_106(X)     \
    X(106)
#define M_REPEAT_CALL_108(X) \
    M_REPEAT_CALL_107(X)     \
    X(107)
#define M_REPEAT_CALL_109(X) \
    M_REPEAT_CALL_108(X)     \
    X(108)
#define M_REPEAT_CALL_110(X) \
    M_REPEAT_CALL_109(X)     \
    X(109)
#define M_REPEAT_CALL_111(X) \
    M_REPEAT_CALL_110(X)     \
    X(110)
#define M_REPEAT_CALL_112(X) \
    M_REPEAT_CALL_111(X)     \
    X(111)
#define M_REPEAT_CALL_113(X) \
    M_REPEAT_CALL_112(X)     \
    X(112)
#define M_REPEAT_CALL_114(X) \
    M_REPEAT_CALL_113(X)     \
    X(113)
#define M_REPEAT_CALL_115(X) \
    M_REPEAT_CALL_114(X)     \
    X(114)
#define M_REPEAT_CALL_116(X) \
    M_REPEAT_CALL_115(X)     \
    X(115)
#define M_REPEAT_CALL_117(X) \
    M_REPEAT_CALL_116(X)     \
    X(116)
#define M_REPEAT_CALL_118(X) \
    M_REPEAT_CALL_117(X)     \
    X(117)
#define M_REPEAT_CALL_119(X) \
    M_REPEAT_CALL_118(X)     \
    X(118)
#define M_REPEAT_CALL_120(X) \
    M_REPEAT_CALL_119(X)     \
    X(119)
#define M_REPEAT_CALL_121(X) \
    M_REPEAT_CALL_120(X)     \
    X(120)
#define M_REPEAT_CALL_122(X) \
    M_REPEAT_CALL_121(X)     \
    X(121)
#define M_REPEAT_CALL_123(X) \
    M_REPEAT_CALL_122(X)     \
    X(122)
#define M_REPEAT_CALL_124(X) \
    M_REPEAT_CALL_123(X)     \
    X(123)
#define M_REPEAT_CALL_125(X) \
    M_REPEAT_CALL_124(X)     \
    X(124)
#define M_REPEAT_CALL_126(X) \
    M_REPEAT_CALL_125(X)     \
    X(125)
#define M_REPEAT_CALL_127(X) \
    M_REPEAT_CALL_126(X)     \
    X(126)
#define M_REPEAT_CALL_128(X) \
    M_REPEAT_CALL_127(X)     \
    X(127)
#define M_REPEAT_CALL_129(X) \
    M_REPEAT_CALL_128(X)     \
    X(128)
#define M_REPEAT_CALL_130(X) \
    M_REPEAT_CALL_129(X)     \
    X(129)
#define M_REPEAT_CALL_131(X) \
    M_REPEAT_CALL_130(X)     \
    X(130)
#define M_REPEAT_CALL_132(X) \
    M_REPEAT_CALL_131(X)     \
    X(131)
#define M_REPEAT_CALL_133(X) \
    M_REPEAT_CALL_132(X)     \
    X(132)
#define M_REPEAT_CALL_134(X) \
    M_REPEAT_CALL_133(X)     \
    X(133)
#define M_REPEAT_CALL_135(X) \
    M_REPEAT_CALL_134(X)     \
    X(134)
#define M_REPEAT_CALL_136(X) \
    M_REPEAT_CALL_135(X)     \
    X(135)
#define M_REPEAT_CALL_137(X) \
    M_REPEAT_CALL_136(X)     \
    X(136)
#define M_REPEAT_CALL_138(X) \
    M_REPEAT_CALL_137(X)     \
    X(137)
#define M_REPEAT_CALL_139(X) \
    M_REPEAT_CALL_138(X)     \
    X(138)
#define M_REPEAT_CALL_140(X) \
    M_REPEAT_CALL_139(X)     \
    X(139)
#define M_REPEAT_CALL_141(X) \
    M_REPEAT_CALL_140(X)     \
    X(140)
#define M_REPEAT_CALL_142(X) \
    M_REPEAT_CALL_141(X)     \
    X(141)
#define M_REPEAT_CALL_143(X) \
    M_REPEAT_CALL_142(X)     \
    X(142)
#define M_REPEAT_CALL_144(X) \
    M_REPEAT_CALL_143(X)     \
    X(143)
#define M_REPEAT_CALL_145(X) \
    M_REPEAT_CALL_144(X)     \
    X(144)
#define M_REPEAT_CALL_146(X) \
    M_REPEAT_CALL_145(X)     \
    X(145)
#define M_REPEAT_CALL_147(X) \
    M_REPEAT_CALL_146(X)     \
    X(146)
#define M_REPEAT_CALL_148(X) \
    M_REPEAT_CALL_147(X)     \
    X(147)
#define M_REPEAT_CALL_149(X) \
    M_REPEAT_CALL_148(X)     \
    X(148)
#define M_REPEAT_CALL_150(X) \
    M_REPEAT_CALL_149(X)     \
    X(149)
#define M_REPEAT_CALL_151(X) \
    M_REPEAT_CALL_150(X)     \
    X(150)
#define M_REPEAT_CALL_152(X) \
    M_REPEAT_CALL_151(X)     \
    X(151)
#define M_REPEAT_CALL_153(X) \
    M_REPEAT_CALL_152(X)     \
    X(152)
#define M_REPEAT_CALL_154(X) \
    M_REPEAT_CALL_153(X)     \
    X(153)
#define M_REPEAT_CALL_155(X) \
    M_REPEAT_CALL_154(X)     \
    X(154)
#define M_REPEAT_CALL_156(X) \
    M_REPEAT_CALL_155(X)     \
    X(155)
#define M_REPEAT_CALL_157(X) \
    M_REPEAT_CALL_156(X)     \
    X(156)
#define M_REPEAT_CALL_158(X) \
    M_REPEAT_CALL_157(X)     \
    X(157)
#define M_REPEAT_CALL_159(X) \
    M_REPEAT_CALL_158(X)     \
    X(158)
#define M_REPEAT_CALL_160(X) \
    M_REPEAT_CALL_159(X)     \
    X(159)
#define M_REPEAT_CALL_161(X) \
    M_REPEAT_CALL_160(X)     \
    X(160)
#define M_REPEAT_CALL_162(X) \
    M_REPEAT_CALL_161(X)     \
    X(161)
#define M_REPEAT_CALL_163(X) \
    M_REPEAT_CALL_162(X)     \
    X(162)
#define M_REPEAT_CALL_164(X) \
    M_REPEAT_CALL_163(X)     \
    X(163)
#define M_REPEAT_CALL_165(X) \
    M_REPEAT_CALL_164(X)     \
    X(164)
#define M_REPEAT_CALL_166(X) \
    M_REPEAT_CALL_165(X)     \
    X(165)
#define M_REPEAT_CALL_167(X) \
    M_REPEAT_CALL_166(X)     \
    X(166)
#define M_REPEAT_CALL_168(X) \
    M_REPEAT_CALL_167(X)     \
    X(167)
#define M_REPEAT_CALL_169(X) \
    M_REPEAT_CALL_168(X)     \
    X(168)
#define M_REPEAT_CALL_170(X) \
    M_REPEAT_CALL_169(X)     \
    X(169)
#define M_REPEAT_CALL_171(X) \
    M_REPEAT_CALL_170(X)     \
    X(170)
#define M_REPEAT_CALL_172(X) \
    M_REPEAT_CALL_171(X)     \
    X(171)
#define M_REPEAT_CALL_173(X) \
    M_REPEAT_CALL_172(X)     \
    X(172)
#define M_REPEAT_CALL_174(X) \
    M_REPEAT_CALL_173(X)     \
    X(173)
#define M_REPEAT_CALL_175(X) \
    M_REPEAT_CALL_174(X)     \
    X(174)
#define M_REPEAT_CALL_176(X) \
    M_REPEAT_CALL_175(X)     \
    X(175)
#define M_REPEAT_CALL_177(X) \
    M_REPEAT_CALL_176(X)     \
    X(176)
#define M_REPEAT_CALL_178(X) \
    M_REPEAT_CALL_177(X)     \
    X(177)
#define M_REPEAT_CALL_179(X) \
    M_REPEAT_CALL_178(X)     \
    X(178)
#define M_REPEAT_CALL_180(X) \
    M_REPEAT_CALL_179(X)     \
    X(179)
#define M_REPEAT_CALL_181(X) \
    M_REPEAT_CALL_180(X)     \
    X(180)
#define M_REPEAT_CALL_182(X) \
    M_REPEAT_CALL_181(X)     \
    X(181)
#define M_REPEAT_CALL_183(X) \
    M_REPEAT_CALL_182(X)     \
    X(182)
#define M_REPEAT_CALL_184(X) \
    M_REPEAT_CALL_183(X)     \
    X(183)
#define M_REPEAT_CALL_185(X) \
    M_REPEAT_CALL_184(X)     \
    X(184)
#define M_REPEAT_CALL_186(X) \
    M_REPEAT_CALL_185(X)     \
    X(185)
#define M_REPEAT_CALL_187(X) \
    M_REPEAT_CALL_186(X)     \
    X(186)
#define M_REPEAT_CALL_188(X) \
    M_REPEAT_CALL_187(X)     \
    X(187)
#define M_REPEAT_CALL_189(X) \
    M_REPEAT_CALL_188(X)     \
    X(188)
#define M_REPEAT_CALL_190(X) \
    M_REPEAT_CALL_189(X)     \
    X(189)
#define M_REPEAT_CALL_191(X) \
    M_REPEAT_CALL_190(X)     \
    X(190)
#define M_REPEAT_CALL_192(X) \
    M_REPEAT_CALL_191(X)     \
    X(191)
#define M_REPEAT_CALL_193(X) \
    M_REPEAT_CALL_192(X)     \
    X(192)
#define M_REPEAT_CALL_194(X) \
    M_REPEAT_CALL_193(X)     \
    X(193)
#define M_REPEAT_CALL_195(X) \
    M_REPEAT_CALL_194(X)     \
    X(194)
#define M_REPEAT_CALL_196(X) \
    M_REPEAT_CALL_195(X)     \
    X(195)
#define M_REPEAT_CALL_197(X) \
    M_REPEAT_CALL_196(X)     \
    X(196)
#define M_REPEAT_CALL_198(X) \
    M_REPEAT_CALL_197(X)     \
    X(197)
#define M_REPEAT_CALL_199(X) \
    M_REPEAT_CALL_198(X)     \
    X(198)
#define M_REPEAT_CALL_200(X) \
    M_REPEAT_CALL_199(X)     \
    X(199)
#define M_REPEAT_CALL_201(X) \
    M_REPEAT_CALL_200(X)     \
    X(200)
#define M_REPEAT_CALL_202(X) \
    M_REPEAT_CALL_201(X)     \
    X(201)
#define M_REPEAT_CALL_203(X) \
    M_REPEAT_CALL_202(X)     \
    X(202)
#define M_REPEAT_CALL_204(X) \
    M_REPEAT_CALL_203(X)     \
    X(203)
#define M_REPEAT_CALL_205(X) \
    M_REPEAT_CALL_204(X)     \
    X(204)
#define M_REPEAT_CALL_206(X) \
    M_REPEAT_CALL_205(X)     \
    X(205)
#define M_REPEAT_CALL_207(X) \
    M_REPEAT_CALL_206(X)     \
    X(206)
#define M_REPEAT_CALL_208(X) \
    M_REPEAT_CALL_207(X)     \
    X(207)
#define M_REPEAT_CALL_209(X) \
    M_REPEAT_CALL_208(X)     \
    X(208)
#define M_REPEAT_CALL_210(X) \
    M_REPEAT_CALL_209(X)     \
    X(209)
#define M_REPEAT_CALL_211(X) \
    M_REPEAT_CALL_210(X)     \
    X(210)
#define M_REPEAT_CALL_212(X) \
    M_REPEAT_CALL_211(X)     \
    X(211)
#define M_REPEAT_CALL_213(X) \
    M_REPEAT_CALL_212(X)     \
    X(212)
#define M_REPEAT_CALL_214(X) \
    M_REPEAT_CALL_213(X)     \
    X(213)
#define M_REPEAT_CALL_215(X) \
    M_REPEAT_CALL_214(X)     \
    X(214)
#define M_REPEAT_CALL_216(X) \
    M_REPEAT_CALL_215(X)     \
    X(215)
#define M_REPEAT_CALL_217(X) \
    M_REPEAT_CALL_216(X)     \
    X(216)
#define M_REPEAT_CALL_218(X) \
    M_REPEAT_CALL_217(X)     \
    X(217)
#define M_REPEAT_CALL_219(X) \
    M_REPEAT_CALL_218(X)     \
    X(218)
#define M_REPEAT_CALL_220(X) \
    M_REPEAT_CALL_219(X)     \
    X(219)
#define M_REPEAT_CALL_221(X) \
    M_REPEAT_CALL_220(X)     \
    X(220)
#define M_REPEAT_CALL_222(X) \
    M_REPEAT_CALL_221(X)     \
    X(221)
#define M_REPEAT_CALL_223(X) \
    M_REPEAT_CALL_222(X)     \
    X(222)
#define M_REPEAT_CALL_224(X) \
    M_REPEAT_CALL_223(X)     \
    X(223)
#define M_REPEAT_CALL_225(X) \
    M_REPEAT_CALL_224(X)     \
    X(224)
#define M_REPEAT_CALL_226(X) \
    M_REPEAT_CALL_225(X)     \
    X(225)
#define M_REPEAT_CALL_227(X) \
    M_REPEAT_CALL_226(X)     \
    X(226)
#define M_REPEAT_CALL_228(X) \
    M_REPEAT_CALL_227(X)     \
    X(227)
#define M_REPEAT_CALL_229(X) \
    M_REPEAT_CALL_228(X)     \
    X(228)
#define M_REPEAT_CALL_230(X) \
    M_REPEAT_CALL_229(X)     \
    X(229)
#define M_REPEAT_CALL_231(X) \
    M_REPEAT_CALL_230(X)     \
    X(230)
#define M_REPEAT_CALL_232(X) \
    M_REPEAT_CALL_231(X)     \
    X(231)
#define M_REPEAT_CALL_233(X) \
    M_REPEAT_CALL_232(X)     \
    X(232)
#define M_REPEAT_CALL_234(X) \
    M_REPEAT_CALL_233(X)     \
    X(233)
#define M_REPEAT_CALL_235(X) \
    M_REPEAT_CALL_234(X)     \
    X(234)
#define M_REPEAT_CALL_236(X) \
    M_REPEAT_CALL_235(X)     \
    X(235)
#define M_REPEAT_CALL_237(X) \
    M_REPEAT_CALL_236(X)     \
    X(236)
#define M_REPEAT_CALL_238(X) \
    M_REPEAT_CALL_237(X)     \
    X(237)
#define M_REPEAT_CALL_239(X) \
    M_REPEAT_CALL_238(X)     \
    X(238)
#define M_REPEAT_CALL_240(X) \
    M_REPEAT_CALL_239(X)     \
    X(239)
#define M_REPEAT_CALL_241(X) \
    M_REPEAT_CALL_240(X)     \
    X(240)
#define M_REPEAT_CALL_242(X) \
    M_REPEAT_CALL_241(X)     \
    X(241)
#define M_REPEAT_CALL_243(X) \
    M_REPEAT_CALL_242(X)     \
    X(242)
#define M_REPEAT_CALL_244(X) \
    M_REPEAT_CALL_243(X)     \
    X(243)
#define M_REPEAT_CALL_245(X) \
    M_REPEAT_CALL_244(X)     \
    X(244)
#define M_REPEAT_CALL_246(X) \
    M_REPEAT_CALL_245(X)     \
    X(245)
#define M_REPEAT_CALL_247(X) \
    M_REPEAT_CALL_246(X)     \
    X(246)
#define M_REPEAT_CALL_248(X) \
    M_REPEAT_CALL_247(X)     \
    X(247)
#define M_REPEAT_CALL_249(X) \
    M_REPEAT_CALL_248(X)     \
    X(248)
#define M_REPEAT_CALL_250(X) \
    M_REPEAT_CALL_249(X)     \
    X(249)
#define M_REPEAT_CALL_251(X) \
    M_REPEAT_CALL_250(X)     \
    X(250)
#define M_REPEAT_CALL_252(X) \
    M_REPEAT_CALL_251(X)     \
    X(251)
#define M_REPEAT_CALL_253(X) \
    M_REPEAT_CALL_252(X)     \
    X(252)
#define M_REPEAT_CALL_254(X) \
    M_REPEAT_CALL_253(X)     \
    X(253)
#define M_REPEAT_CALL_255(X) \
    M_REPEAT_CALL_254(X)     \
    X(254)
#define M_REPEAT_CALL_256(X) \
    M_REPEAT_CALL_255(X)     \
    X(255)
#define M_EXPAND(...) __VA_ARGS__

#define M_REPEAT_CALL__(N, X)   \
    M_EXPAND(M_REPEAT_CALL_##N) \
    (X)
#define M_REPEAT_CALL_(N, X) M_REPEAT_CALL__(N, X)
#define M_REPEAT_CALL(N, X) M_REPEAT_CALL_(M_EXPAND(N), X)

#endif
